<?php include 'header.phtml' ?>

<div id="main-container">
	<h1>Créer un nouveau héro</h1>

	<form action="creation.php" method="post">
		<label>Nom</label><input name="name"><br>
		<label>Point de vie</label><input name="hp"><br>
		<label>Armure</label><input name="armor"><br>
		<label>Avatar</label><input name="avatar"><br>
		<button>Créer</button>
	</form>
</div>

<?php include 'footer.phtml' ?>